- name: Run frontend container
  docker_container:
    name: frontend
    image: rorodu92/tp-devops-frontend
    state: started
    pull: true
    recreate: true
    force_kill: true
    restart_policy: always
    networks:
      - name: app-network
    env:
      NODE_ENV: production