- hosts: all
  vars_files:
    - secrets.yml
  gather_facts: true
  become: true
  roles:
      - docker
      - create_network
      - launch_database
      - launch_app
      - launch_frontend
      - launch_proxy
  tasks:
   - name: Test connection
     ping: