name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
    branches: [main]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-24.04
    # Only run if the test workflow succeeded and we're on main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: true
          
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest